### ISSUE TITLE
Using RRT in Occupancy Grid [ROS Hydro]

### ISSUE THREAD

**Issue by ktiwari9** [srl-freiburg/srl_global_planner#1]
Hi guys,
I am using ROS Hydro and I already have generated an Occupancy Grid (attached Screencap) and I used this repo https://github.com/clearpathrobotics/occupancy_grid_utils for visualizing the OGM. I want to take this as an input and run a graph search algorithm to generate a path to go from pre-defined start position to pre-defined goal position but the path must only be in the free space of the occupancy grid. How can i use your code to achieve this ?
![ogm](https://cloud.githubusercontent.com/assets/5789469/9486153/63987ee0-4bfe-11e5-9223-d2e5ee5e87e5.png)
 P.S. I am not using move_base to send my goals.

**Comment by palmieri** [comment]
Hi,

currently the srl_global_planner is a move_base plug-in. You have to use move_base and specify as global planner the srl_global_planner. To plan on your occupancy map, you should publish it on the /map frame. For other details please see the move_base wiki.

Best,

LP
