### ISSUE TITLE
Message files for compilation

### ISSUE THREAD

**Issue by LiliMeng** [srl-freiburg/srl_global_planner#3]
Hi,

```
  Thanks a lot for contributing this open source file!

  We cannot find the following message files:
   spencer_tracking_msgs
   spencer_nav_msgs
   spencer_control_msgs

    Could you provide some help?
    Thanks a lot! 
```

**Comment by makokal** [comment]
Sorry about that, you can grab the messages from [https://github.com/spencer-project/spencer_messages](https://github.com/spencer-project/spencer_messages) for now, before we cherry pick the ones used here.

**Comment by LiliMeng** [comment]
Thanks a lot for this quick and helpful reply! 

It has other compile errors :

```
/home/lci/catkin_ws_new/src/srl_global_planner/src/srl_global_planner.cpp: In member function ‘virtual void srl_global_planner::Srl_global_planner::initialize(std::string, costmap_2d::Costmap2DROS*)’:
/home/lci/catkin_ws_new/src/srl_global_planner/src/srl_global_planner.cpp:2366:34: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getTransformListener’
         listener = costmap_ros_->getTransformListener();
                                  ^
make[2]: *** [srl_global_planner/CMakeFiles/srl_global_planner.dir/src/srl_global_planner.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object srl_global_planner/CMakeFiles/srl_global_planner.dir/include/srl_global_planner/trajectory.cpp.o
make[1]: *** [srl_global_planner/CMakeFiles/srl_global_planner.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
```

Thanks again!

**Comment by makokal** [comment]
@palmieri can you look at this?

**Comment by palmieri** [comment]
Hi LiliMeng,

This is something related to a mod that I have done to the costmap_2d in the ros-navigation repository but only locally. It was made to avoid the instantiation of multiple trasform_listeners in  move_base, which could cause tf efficiency problems in complex robotics systems. 

I need some time to fix it, sorry quite busy in these days. In principle you could create  a new tf_listener in that line.

**Comment by zychaoqun** [comment]
Hi @palmieri 
    what kind of tf_listener shall we set to avoid the problem:
   listener = costmap_ros_->getTransformListener();

        ??? Thanks a lot

**Comment by healthysong** [comment]
I also have the same problem.Have you dealt that ?

**Comment by opan08** [comment]
replace:
listener = costmap_ros_->getTransformListener();
with:
listener = new tf::TransformListener(ros::Duration(10));
