### ISSUE TITLE
Spencer project packages

### ISSUE THREAD

**Issue by ghost** [srl-freiburg/srl_global_planner#4]
I am trying to launch srl_global_planner but here are many spencer project packages that are required like spencer_tracking_utils, social_compliance_layer and spencer_navigation. 

I was able to find the first two on github but couldn't find spencer_navigation. As a workaround I changed the launch file to use analogous files from the srl_global_planner instead. But launching after that gives more errors and warnings. 

Is there any repository with the required spencer packages? Any help will be much appreciated

**Comment by prodigystd** [comment]
I have the same problem.

**Comment by tcjcxy30** [comment]
I have the same problem too... @rohit-murthy  @prodigystd   You find the way to fix it now?

**Comment by gongyue666** [comment]
+1

**Comment by palmieri** [comment]
Hi all, 
sorry, it's a very busy time. Regarding the spencer_nav_msgs, you can comment it out from the CMakeLists.txt and package.xml files. This version of the code does not use it.

**Comment by gongyue666** [comment]
thx for your reply,and catkin_make is ok ,but when launch many errors comes most of which are about tf, can not run anyway.
