### ISSUE TITLE
'class costmap_2d::Costmap2DROS’ has no member named ‘getTransformListener’

### ISSUE THREAD

**Issue by tcjcxy30** [srl-freiburg/srl_global_planner#6]
hi:
I follow the readme and install srl_global_planner with 'catkin_make'. There is an error with no member and how can i fix it?

[ 20%] Building CXX object srl_planner/srl_global_planner/CMakeFiles/srl_global_planner.dir/src/srl_global_planner.cpp.o
[ 20%] Built target tag_node
/home/cxy/catkin_ws/src/srl_planner/srl_global_planner/src/srl_global_planner.cpp: In member function ‘virtual void srl_global_planner::Srl_global_planner::initialize(std::string, costmap_2d::Costmap2DROS*)’:
/home/cxy/catkin_ws/src/srl_planner/srl_global_planner/src/srl_global_planner.cpp:2366:34: error: ‘class costmap_2d::Costmap2DROS’ has no member named ‘getTransformListener’
         listener = costmap_ros_->getTransformListener();
                                  ^
make[2]: *** [srl_planner/srl_global_planner/CMakeFiles/srl_global_planner.dir/src/srl_global_planner.cpp.o] Error 1
make[1]: *** [srl_planner/srl_global_planner/CMakeFiles/srl_global_planner.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

I have seen the closed issues and someone also ask this question, and i don't kown what kind of tf_listener shall we set to avoid the problem:
listener = costmap_ros_->getTransformListener();

Thank you a lot

**Comment by palmieri** [comment]
Hi, 

sorry for the late answer. You may instantiate [your own tf listener](http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28C%2B%2B%29).
